"""
app/constants.py — all immutable data: i18n strings, recipes, holiday tables, app config.
"""
from pathlib import Path

ROOT         = Path(__file__).parent.parent
DEFAULT_CSV  = ROOT / "data" / "boulangerie.csv"

REQUIRED_COLS = {"date", "produit", "quantite_vendue"}
WEEKEND_DAYS  = {"Friday", "Saturday"}
BUFFER_RATE   = 1.15
PEAK_THRESH   = 1.30
UNIT_OPTIONS  = ["g", "kg", "ml", "L", "piece", "tbsp", "tsp", "oz", "portion"]

EN_DAYS_IDX = {
    "Monday": 0, "Tuesday": 1, "Wednesday": 2, "Thursday": 3,
    "Friday": 4, "Saturday": 5, "Sunday": 6,
}

# ── Moroccan fixed public holidays (month, day, name) ────────────────────────
MAROC_FIXED_HOLIDAYS = [
    (1,  1,  "Jour de l'An"),
    (1,  11, "Manifeste de l'Indépendance"),
    (5,  1,  "Fête du Travail"),
    (7,  30, "Fête du Trône"),
    (8,  14, "Allégeance des Provinces du Sud"),
    (8,  20, "Révolution du Roi et du Peuple"),
    (8,  21, "Fête de la Jeunesse"),
    (11, 6,  "Marche Verte"),
    (11, 18, "Fête de l'Indépendance"),
]

ISLAMIC_HOLIDAYS: dict[int, list[tuple[str, str]]] = {
    2022: [("2022-05-02","Aïd al-Fitr"),("2022-05-03","Aïd al-Fitr J2"),
           ("2022-07-09","Aïd al-Adha"),("2022-07-10","Aïd al-Adha J2"),
           ("2022-07-30","Aïd al-Hijra"),("2022-10-08","Mawlid")],
    2023: [("2023-04-21","Aïd al-Fitr"),("2023-04-22","Aïd al-Fitr J2"),
           ("2023-06-28","Aïd al-Adha"),("2023-06-29","Aïd al-Adha J2"),
           ("2023-07-19","Aïd al-Hijra"),("2023-09-27","Mawlid")],
    2024: [("2024-04-10","Aïd al-Fitr"),("2024-04-11","Aïd al-Fitr J2"),
           ("2024-06-17","Aïd al-Adha"),("2024-06-18","Aïd al-Adha J2"),
           ("2024-07-08","Aïd al-Hijra"),("2024-09-15","Mawlid")],
    2025: [("2025-03-31","Aïd al-Fitr"),("2025-04-01","Aïd al-Fitr J2"),
           ("2025-06-07","Aïd al-Adha"),("2025-06-08","Aïd al-Adha J2"),
           ("2025-06-26","Aïd al-Hijra"),("2025-09-04","Mawlid")],
    2026: [("2026-03-20","Aïd al-Fitr"),("2026-03-21","Aïd al-Fitr J2"),
           ("2026-05-27","Aïd al-Adha"),("2026-05-28","Aïd al-Adha J2"),
           ("2026-06-16","Aïd al-Hijra"),("2026-08-25","Mawlid")],
    2027: [("2027-03-09","Aïd al-Fitr"),("2027-03-10","Aïd al-Fitr J2"),
           ("2027-05-16","Aïd al-Adha"),("2027-05-17","Aïd al-Adha J2"),
           ("2027-06-06","Aïd al-Hijra"),("2027-08-14","Mawlid")],
}

RAMADAN_DATES: dict[int, tuple[str, str]] = {
    2022: ("2022-04-02", "2022-05-01"),
    2023: ("2023-03-23", "2023-04-20"),
    2024: ("2024-03-11", "2024-04-09"),
    2025: ("2025-03-01", "2025-03-29"),
    2026: ("2026-02-18", "2026-03-18"),
    2027: ("2027-02-07", "2027-03-08"),
}

# ── i18n strings ──────────────────────────────────────────────────────────────
TRANS: dict[str, dict] = {
    "fr": {
        # ── Main navigation (4 tabs) ──────────────────────────────────────────
        "nav_today":       "Aujourd'hui",
        "nav_forecasts":   "Prévisions",
        "nav_finance":     "Finances",
        "nav_analytics":   "Analyses",
        # ── Legacy nav keys (kept for compatibility) ──────────────────────────
        "nav_dashboard":       "Tableau de bord",
        "nav_saisie":          "Saisie des ventes",
        "nav_overview":        "Vue d'ensemble",
        "nav_forecast":        "Prévisions",
        "nav_analyse":         "Analyse",
        "nav_finances":        "Finances",
        "nav_recommendations": "Recommandations",
        "nav_products":        "Produits",
        "nav_shopping":        "Liste de courses",
        "nav_conseils":        "Conseils",
        "nav_about":           "À propos",
        # ── Sidebar ───────────────────────────────────────────────────────────
        "sidebar_file":        "FICHIER DE VENTES",
        "sidebar_demo":        "Boulangerie Atlas (démo) — importez votre fichier ci-dessus.",
        "sidebar_ramadan":     "Mode Ramadan",
        "sidebar_ramadan_help":"Active les alertes Iftar, produits spéciaux et indicateurs sur les graphiques.",
        "sidebar_lite":        "Mode économique",
        "sidebar_lite_help":   "Désactive les prévisions IA (Prophet) pour économiser la bande passante. Idéal avec une connexion faible.",
        # ── Onboarding ────────────────────────────────────────────────────────
        "onboard_title":       "Bienvenue sur FoodCast",
        "onboard_sub":         "Importez vos ventes pour voir vos prévisions et conseils en temps réel.",
        "onboard_load_btn":    "Charger un CSV",
        "onboard_demo_btn":    "Utiliser les données démo",
        "onboard_demo_hint":   "Boulangerie Atlas · 27 mois · 12 produits",
        # ── Dashboard ─────────────────────────────────────────────────────────
        "dash_title":          "Tableau de bord",
        "sec_today":           "Résumé du jour",
        "sec_perf":            "Indicateur de performance",
        "sec_ranking":         "Classement des produits",
        "sec_week":            "Ventes de la semaine",
        "sec_history":         "Historique — 30 derniers jours",
        # ── KPIs ─────────────────────────────────────────────────────────────
        "kpi_sold":            "Unités vendues",
        "kpi_yesterday":       "vs hier",
        "kpi_avg":             "vs moyenne",
        "kpi_best":            "Meilleur produit du jour",
        "kpi_avg_day":         "Moyenne / jour ouvert",
        "kpi_best_day_ever":   "Record historique",
        "kpi_open_days":       "Jours ouverts",
        "kpi_yesterday_sub":   "hier : {qty} {u}",
        "kpi_avg_sub":         "moy. : {avg:.0f} {u}/j",
        # ── Performance ──────────────────────────────────────────────────────
        "perf_good":           "Bonne journée",
        "perf_avg":            "Journée moyenne",
        "perf_bad":            "Mauvaise journée",
        "perf_good_sub":       "Bien au-dessus de la moyenne",
        "perf_avg_sub":        "Dans la fourchette habituelle",
        "perf_bad_sub":        "En dessous de la moyenne",
        "perf_vs":             "de la moyenne",
        # ── Ranking ──────────────────────────────────────────────────────────
        "rank_pos":            "#",
        "rank_product":        "Produit",
        "rank_total":          "Total vendu",
        "rank_share":          "Part",
        "rank_trend":          "Tendance",
        "rank_caption":        "↗ hausse · → stable · ↘ baisse (comparaison 30 derniers jours vs 30 jours précédents)",
        # ── History table ─────────────────────────────────────────────────────
        "hist_date":           "Date",
        "hist_day":            "Jour",
        "hist_qty":            "Quantité",
        "hist_vs_avg":         "vs moy.",
        "hist_perf":           "Bilan",
        # ── Misc ─────────────────────────────────────────────────────────────
        "days":                ["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"],
        "units":               "unités",
        "lang_label":          "Langue",
        # ── Saisie ───────────────────────────────────────────────────────────
        "saisie_title":        "Saisie des ventes",
        "saisie_sub":          "Entrez vos ventes du jour sans modifier votre fichier CSV. Téléchargez ensuite le fichier complet pour le réimporter.",
        "saisie_nofile":       "Aucun fichier chargé — vous pouvez saisir vos ventes manuellement. Téléchargez ensuite le CSV généré et importez-le comme fichier de données.",
        "saisie_new_prod":     "Ajouter un produit à la liste",
        "saisie_add_btn":      "Ajouter",
        "saisie_date_label":   "Date des ventes",
        "saisie_save_btn":     "Enregistrer les ventes",
        "saisie_save_btn2":    "Enregistrer",
        "saisie_sec_entry":    "Ventes du jour",
        "saisie_history":      "Historique des saisies manuelles",
        "saisie_export":       "Exporter / Synchroniser",
        "saisie_sync_tip":     "💡 Vos saisies sont conservées pendant cette session. Téléchargez le fichier complet ci-dessous pour ne pas les perdre, puis importez-le au prochain démarrage.",
        "saisie_download":     "Télécharger fichier complet (CSV + saisies)",
        "saisie_clear":        "Tout effacer",
        "saisie_empty":        "Aucune saisie manuelle pour le moment. Utilisez le formulaire ci-dessus.",
        "saisie_success":      "{n} produit(s) enregistré(s) pour le {d}.",
        "saisie_warn":         "Entrez au moins une quantité > 0.",
        "saisie_kpi_days":     "Jours saisis",
        "saisie_kpi_days_sub": "via saisie manuelle",
        "saisie_kpi_total":    "Total saisi",
        "saisie_kpi_total_sub":"unités au total",
        "saisie_already_csv":  "Déjà dans votre CSV pour cette date.",
        # ── Dialog saisie rapide ──────────────────────────────────────────────
        "dialog_add_title":    "Ajouter des ventes",
        "dialog_add_sub":      "Les saisies sont conservées pendant cette session. Exportez le CSV pour les garder.",
        "dialog_btn_open":     "+ Ajouter des ventes",
        # ── Forecast ─────────────────────────────────────────────────────────
        "forecast_title":      "Prévisions des ventes",
        "forecast_sub":        "Prévisions IA Prophet avec prise en compte des fêtes marocaines.",
        "forecast_lite_banner":"⚡ Mode économique activé — Prévisions IA désactivées. Désactivez-le dans la barre latérale pour voir les prévisions Prophet.",
        "forecast_lite_section":"Tendance récente (30 derniers jours)",
        "forecast_horizon":    "Combien de jours ?",
        "forecast_horizon_fmt":"{n} jours",
        "forecast_acc_good":   "Très bonne",
        "forecast_acc_ok":     "Bonne",
        "forecast_acc_fair":   "Correcte",
        "forecast_acc_na":     "N/D",
        "forecast_acc_sub":    "erreur moy. : {mae} unités/j",
        "forecast_acc_label":  "Précision des prévisions",
        "forecast_acc_nodata": "Pas assez de données",
        "forecast_spinner":    "Chargement de votre prévision...",
        "forecast_chart_sec":  "Historique + prévision {n} jours",
        "forecast_history":    "Ventes passées",
        "forecast_pred":       "Prévision IA",
        "forecast_range":      "Plage prévue",
        "forecast_fc_start":   "Début prévision ({d})",
        "forecast_peaks":      "Alertes — Pics imminents",
        "forecast_ram_sec":    "Mode Ramadan — Jours concernés",
        "forecast_ram_msg":    "**{n} jours** de la prévision tombent pendant le Ramadan. Les ventes du soir (Iftar) peuvent représenter 60–80% du chiffre journalier. Préparez davantage de **Harira, Chebakia, Briouates** et boissons sucrées.",
        "forecast_weekly":     "Résumé hebdomadaire",
        "forecast_monthly":    "Résumé mensuel",
        "forecast_weekly_cols":["Semaine","Jours","Total prévu","Moy. jour","Min prévu","Max prévu"],
        "forecast_monthly_cols":["Mois","Total prévu","Moy. jour","Min prévu","Max prévu"],
        # ── Recommendations (Stock à préparer) ───────────────────────────────
        "reco_title":          "Stock à préparer",
        "reco_sub":            "7 prochains jours · buffer +15%",
        "reco_spinner":        "Calcul du plan de stock...",
        "reco_summary":        "{total} unités à préparer cette semaine",
        "reco_summary_sub":    "prévision : {pred} + 15% buffer",
        "reco_plan":           "Plan journalier",
        "reco_col_date":       "Date",
        "reco_col_day":        "Jour",
        "reco_col_expected":   "Ventes prévues",
        "reco_col_stock":      "À préparer",
        "reco_col_peak":       "Jour de pointe",
        "reco_col_risk":       "Risque",
        "reco_risk_high":      "Élevé",
        "reco_risk_med":       "Moyen",
        "reco_risk_low":       "Faible",
        "reco_footer":         "Moy. journalière : {avg} unités · buffer : +15% · Élevé = +30% vs moyenne · Min/Max = fourchette de confiance",
        "reco_no_peak":        "Aucun pic extraordinaire prévu. Opérations normales recommandées.",
        # ── Analyse ──────────────────────────────────────────────────────────
        "analyse_title":       "Analyse avancée",
        "analyse_sub":         "Comparaison semaines, prévisions par produit, calendrier des fêtes marocaines et meilleure heure de vente.",
        "analyse_spinner":     "Calcul des prévisions...",
        "analyse_week":        "Semaine en cours vs semaine dernière",
        "analyse_cur_week":    "Semaine en cours",
        "analyse_cur_week_sub":"7 derniers jours",
        "analyse_prev_week":   "Semaine dernière",
        "analyse_prev_week_sub":"7 jours précédents",
        "analyse_delta":       "Évolution",
        "analyse_units_sold":  "Unités vendues",
        "analyse_hour":        "Meilleure heure de vente",
        "analyse_best_hour":   "Meilleure heure",
        "analyse_peak_avg":    "Pic moyen : {qty:.1f} unités",
        "analyse_no_hour":     "Pour activer cette fonctionnalité, ajoutez une colonne **`heure`** (0–23) à votre fichier CSV. Exemple : `2024-01-15, Pizza Margherita, 12, 8`",
        "analyse_prod":        "Prévision par produit",
        "analyse_prod_pick":   "Choisir un produit",
        "analyse_horizon":     "Horizon",
        "analyse_horizon_fmt": "{n} jours",
        "analyse_prod_lite":   "⚡ Mode économique — prévisions par produit désactivées.",
        "analyse_prod_empty":  "Aucun produit trouvé dans vos données.",
        "analyse_prod_nodata": "Pas assez de données pour **{p}** ({n} jours — minimum 30).",
        "analyse_prod_spinner":"Prévision pour {p}...",
        "analyse_prod_hist":   "Moy. historique",
        "analyse_prod_next7":  "Prévu (7 prochains j.)",
        "analyse_prod_units":  "unités/jour (jours ouverts)",
        "analyse_prod_total":  "unités au total",
        "analyse_interval":    "Intervalle",
        "analyse_pred_label":  "Prévision IA",
        "analyse_hist_label":  "Historique",
        "analyse_fc_start":    "Début prévision",
        "analyse_calendar":    "Calendrier des fêtes marocaines",
        "analyse_cal_nat":     "Fête nationale",
        "analyse_cal_isl":     "Fête islamique",
        "analyse_cal_ram":     "Ramadan",
        "analyse_ram_msg":     "**Mode Ramadan activé** — Pendant le Ramadan, vos ventes se concentrent sur la tranche **19h – 23h** (Iftar & Tarawih). Préparez davantage de : Harira, Chebakia, Sellou, Briouates, Shabakiya, jus frais et dattes. Réduisez les préparations matinales de 30–40%.",
        "analyse_trend_up":    "hausse",
        "analyse_trend_stable":"stable",
        "analyse_trend_down":  "baisse",
        "analyse_trend_caption":"↗ {up} · → {stable} · ↘ {down} (comparaison 30 derniers jours vs 30 jours précédents)",
        # ── Overview ─────────────────────────────────────────────────────────
        "overview_title":      "Vue d'ensemble",
        "overview_sub":        "{n} lignes · {start} → {end}",
        "overview_kpi_total":  "Total vendu",
        "overview_kpi_best":   "Meilleur produit",
        "overview_kpi_avg":    "Moy. journalière",
        "overview_kpi_busiest":"Jour le + chargé",
        "overview_trend":      "Tendance des ventes",
        "overview_filter":     "Filtrer la période",
        "overview_breakdown":  "Répartition produits",
        "overview_health":     "Santé des données",
        "overview_health_ok":  "OK",
        "overview_health_warn":"Avertissement",
        "overview_health_err": "Erreur",
        # ── Finances ─────────────────────────────────────────────────────────
        "fin_title":           "Finances & Rentabilité",
        "fin_sub":             "Chiffre d'affaires, marges, objectifs et estimation du bénéfice mensuel.",
        "fin_config":          "Configurer les prix de vente et coûts de revient",
        "fin_config_caption":  "Entrez le **prix de vente** (ce que vous encaissez) et le **coût unitaire** (ingrédients + emballage) pour chaque produit. Toutes les valeurs sont en **MAD**.",
        "fin_auto_price":      "Colonne `prix_unitaire` détectée dans votre fichier — prix pré-remplis.",
        "fin_col_prod":        "Produit",
        "fin_col_price":       "Prix vente (MAD)",
        "fin_col_cost":        "Coût unitaire (MAD)",
        "fin_col_price_help":  "Prix auquel vous vendez une portion/unité",
        "fin_col_cost_help":   "Coût total d'ingrédients + emballage par unité produite",
        "fin_warn_no_price":   "Aucun prix de vente configuré — les métriques financières afficheront 0 MAD. Renseignez les prix dans le tableau ci-dessus pour activer toutes les analyses.",
        "fin_ca_section":      "Chiffre d'affaires",
        "fin_kpi_day":         "CA du jour",
        "fin_kpi_week":        "CA de la semaine",
        "fin_kpi_month":       "CA du mois",
        "fin_kpi_margin":      "Marge brute mois",
        "fin_margin_sub":      "marge : {m}",
        "fin_margin_pct":      "{pct:.1f}% du CA",
        "fin_target_section":  "Objectif de CA journalier",
        "fin_target_input":    "Objectif (MAD/jour)",
        "fin_target_above":    "{pct:.0f}% atteint · {ca} / objectif {target}",
        "fin_target_days":     "Jours ayant atteint l'objectif dans l'historique : **{n} / {total}**",
        "fin_target_empty":    "Entrez un objectif à gauche pour voir votre progression.",
        "fin_ca_series":       "CA journalier",
        "fin_cost_series":     "Coût matières premières",
        "fin_target_line":     "Objectif {t}/j",
        "fin_prod_section":    "Produit le plus rentable vs le plus vendu",
        "fin_best_seller":     "Plus vendu",
        "fin_best_margin":     "Plus rentable",
        "fin_bubble_x":        "Unités vendues",
        "fin_bubble_y":        "Marge / unité (MAD)",
        "fin_bubble_size":     "CA total (MAD)",
        "fin_table_cols":      ["Produit","Unités vendues","CA total","Coût total MP","Marge brute","Marge %","Marge/unité"],
        "fin_no_price_info":   "Configurez les prix ci-dessus pour voir cette analyse.",
        "fin_monthly_section": "Recettes vs dépenses matières premières",
        "fin_rev_series":      "Recettes (CA)",
        "fin_mp_series":       "Coût MP",
        "fin_margin_series":   "Marge brute",
        "fin_profit_section":  "Estimation du bénéfice mensuel",
        "fin_month_cols":      ["Mois","CA (MAD)","MP (MAD)","Marge (MAD)","Marge %"],
        "fin_total_sub":       "CA : {ca} · Coût MP : {cout} · Taux : {pct:.1f}%",
        "fin_total_label":     "Marge brute totale sur toute la période",
        "fin_no_config_info":  "Configurez les prix et coûts ci-dessus pour activer cette section.",
        "fin_footer":          "Marge brute = CA − Coût matières premières. Elle ne tient pas compte du loyer, de la masse salariale ni des charges fixes. Une marge brute ≥ 60% est généralement saine pour la restauration rapide.",
        # ── Products (catalogue) ─────────────────────────────────────────────
        "products_title":          "Mes produits",
        "products_sub":            "Activez/désactivez les produits dans les calculs et prévisions.",
        "products_kpi_total":      "Total produits",
        "products_kpi_active":     "Produits actifs",
        "products_kpi_custom":     "Ajoutés par vous",
        "products_list_title":     "Liste des produits",
        "products_list_caption":   "Cochez/décochez **Actif** pour inclure ou exclure un produit. Les produits de votre CSV ne peuvent pas être supprimés.",
        "products_col_dish":       "Produit",
        "products_col_source":     "Source",
        "products_col_share":      "Part des ventes",
        "products_col_recipe":     "Recette",
        "products_col_active":     "Actif",
        "products_source_csv":     "Depuis vos données",
        "products_source_custom":  "Ajouté par vous",
        "products_add_title":      "Ajouter un produit",
        "products_add_caption":    "Ajoutez un produit absent de votre CSV. Définissez ses ingrédients dans Liste de courses.",
        "products_add_placeholder":"ex. Frites, Nuggets…",
        "products_add_btn":        "Ajouter",
        "products_add_exists":     "**{name}** est déjà dans votre catalogue.",
        "products_add_success":    "**{name}** ajouté ! Définissez ses ingrédients dans Liste de courses.",
        "products_del_title":      "Supprimer un produit",
        "products_del_caption":    "Seuls les produits que vous avez ajoutés peuvent être supprimés.",
        "products_del_btn":        "Supprimer",
        "products_info":           "Les produits de votre CSV peuvent être désactivés mais pas supprimés — leur historique est nécessaire aux prévisions. Les produits ajoutés manuellement peuvent être supprimés librement.",
        # ── Shopping list ─────────────────────────────────────────────────────
        "shop_title":          "Liste de courses",
        "shop_sub":            "Ingrédients pour les 7 prochains jours, calculés depuis vos recettes et prévisions.",
        "shop_ingredients_title":  "Ingrédients par plat",
        "shop_ingredients_caption":"Quantités pour une portion. Modifiez librement noms, quantités et unités.",
        "shop_stock_title":        "Ce que vous avez déjà",
        "shop_stock_caption":      "Entrez votre stock actuel. Seul ce qui manque apparaîtra dans la commande.",
        "shop_needs_title":        "Besoins journaliers — 7 prochains jours",
        "shop_order_title":        "Quoi acheter",
        "shop_stockout_title":     "Quand serez-vous en rupture ?",
        "shop_kpi_tobuy":          "Ingrédients à acheter",
        "shop_kpi_ok":             "Déjà en stock",
        "shop_kpi_first":          "Première rupture",
        "shop_col_ing":            "Ingrédient",
        "shop_col_unit":           "Unité",
        "shop_col_need":           "Besoin 7j (+15%)",
        "shop_col_have":           "En stock",
        "shop_col_buy":            "À acheter",
        "shop_col_status":         "Statut",
        "shop_status_ok":          "OK",
        "shop_status_order":       "Commander",
        "shop_status_critical":    "Critique",
        "shop_col_instock":        "En stock",
        "shop_col_perday":         "Consommé/jour",
        "shop_col_runout":         "Date de rupture",
        "shop_col_urgency":        "Urgence",
        "shop_urg_ok":             "OK",
        "shop_urg_soon":           "Très bientôt",
        "shop_urg_week":           "Cette semaine",
        "shop_urg_later":          "Plus tard",
        "shop_caption":            "Besoin = prévision × ingrédients × +15% buffer · À acheter = Besoin − Stock",
        "shop_no_ing":             "Aucun ingrédient défini. Remplissez le tableau ci-dessus.",
        "shop_spinner":            "Calcul de vos besoins...",
        # ── Conseils ─────────────────────────────────────────────────────────
        "conseils_hero_title": "Aide à la décision",
        "conseils_hero_sub":   "Conseils personnalisés basés sur votre historique — mis à jour en temps réel selon vos données.",
        "conseils_pdj":        "⭐ Produit du jour à mettre en avant",
        "conseils_pdj_badge":  "Mettre en avant aujourd'hui",
        "conseils_pdj_score":  "Score {s}/100 | Moyenne {d} : {qty:.0f} unités{margin}",
        "conseils_pdj_margin": " | Marge : {m:.1f} MAD/unité",
        "conseils_pdj_empty":  "Pas assez de données pour calculer le produit du jour.",
        "conseils_prep":       "📋 Prépare plus — les 7 prochains jours",
        "conseils_prep_normal":"Journée habituelle — pas de pic identifié.",
        "conseils_promo":      "🏷️ Suggestions de prix promotionnel",
        "conseils_promo_thresh":"Seuil de baisse pour déclencher une promo (%)",
        "conseils_promo_help": "Un produit est signalé si ses ventes des 7 derniers jours ont chuté de X% par rapport aux 30 derniers jours.",
        "conseils_promo_note": "Prix promotionnel calculé en appliquant la remise au prix unitaire configuré dans Finances.",
        "conseils_promo_config":"configurez le prix",
        "conseils_promo_ok":   "✅ Aucun produit en baisse significative sur les 7 derniers jours.",
        "conseils_dormant":    "😴 Alertes — produits non vendus récemment",
        "conseils_dormant_slider":"Signaler si absent depuis (jours)",
        "conseils_dormant_help":"Un produit est signalé s'il n'apparaît pas dans vos ventes depuis X jours.",
        "conseils_dormant_since":"Dernière vente : {d} — absent depuis {n} jours",
        "conseils_dormant_never":"Dernière vente : jamais — absent depuis +{n} jours",
        "conseils_dormant_ok": "✅ Tous les produits ont été vendus dans les derniers jours.",
        "conseils_seasonal":   "🌿 Idées de nouveaux produits — saison & événements",
        "conseils_seasonal_note":"Suggestions basées sur les tendances du marché marocain et la saisonnalité locale. Adaptez-les à votre clientèle.",
        "conseils_seasonal_empty":"Aucune suggestion saisonnière disponible pour cette période.",
        "conseils_ram_current":"Ramadan — en ce moment",
        "conseils_ram_soon":   "Ramadan — dans 30 jours",
        "conseils_month_now":  "{m} — produits de saison",
        "conseils_month_next": "{m} — anticipez le mois prochain",
        # ── About ─────────────────────────────────────────────────────────────
        "about_title":         "À propos",
        "about_what_title":    "Qu'est-ce que FoodCast ?",
        "about_what_body":     "Dashboard de prévision des ventes pour petites enseignes alimentaires. Importez votre historique CSV, obtenez des prévisions Prophet, et décidez quoi préparer et acheter — sans compétences techniques.",
        "about_format_title":  "Format de votre fichier CSV",
        "about_dl_sample":     "Télécharger un CSV exemple",
        "about_stack_title":   "Construit avec",
        "about_version":       "v{v} · FoodCast © 2025",
        # ── Sub-tab labels ────────────────────────────────────────────────────
        "tab_ranking":         "Classement",
        "tab_conseils":        "Conseils",
        "tab_forecast_global": "Prévision globale",
        "tab_reco":            "Stock à préparer",
        "tab_per_product":     "Par produit",
        "tab_shopping":        "Liste de courses",
        "tab_overview":        "Vue d'ensemble",
        "tab_trends":          "Tendances",
        "tab_catalogue":       "Catalogue",
    },

    "ar": {
        # ── Main navigation ───────────────────────────────────────────────────
        "nav_today":       "اليوم",
        "nav_forecasts":   "التوقعات",
        "nav_finance":     "الماليات",
        "nav_analytics":   "التحليلات",
        # ── Legacy ───────────────────────────────────────────────────────────
        "nav_dashboard":       "لوحة القيادة",
        "nav_saisie":          "إدخال المبيعات",
        "nav_overview":        "نظرة عامة",
        "nav_forecast":        "التوقعات",
        "nav_analyse":         "التحليل",
        "nav_finances":        "الماليات",
        "nav_recommendations": "التوصيات",
        "nav_products":        "المنتجات",
        "nav_shopping":        "قائمة التسوق",
        "nav_conseils":        "النصائح",
        "nav_about":           "حول",
        # ── Sidebar ───────────────────────────────────────────────────────────
        "sidebar_file":        "ملف المبيعات",
        "sidebar_demo":        "مخبزة أطلس (تجريبي) — استورد ملفك أعلاه.",
        "sidebar_ramadan":     "وضع رمضان",
        "sidebar_ramadan_help":"تفعيل تنبيهات الإفطار والمنتجات الخاصة.",
        "sidebar_lite":        "الوضع الاقتصادي",
        "sidebar_lite_help":   "تعطيل توقعات الذكاء الاصطناعي لتوفير النطاق الترددي.",
        # ── Onboarding ────────────────────────────────────────────────────────
        "onboard_title":       "مرحباً بك في FoodCast",
        "onboard_sub":         "استورد مبيعاتك لرؤية التوقعات والنصائح في الوقت الفعلي.",
        "onboard_load_btn":    "تحميل CSV",
        "onboard_demo_btn":    "استخدام البيانات التجريبية",
        "onboard_demo_hint":   "مخبزة أطلس · 27 شهراً · 12 منتجاً",
        # ── Dashboard ─────────────────────────────────────────────────────────
        "dash_title":          "لوحة القيادة",
        "sec_today":           "ملخص اليوم",
        "sec_perf":            "مؤشر الأداء",
        "sec_ranking":         "ترتيب المنتجات",
        "sec_week":            "مبيعات الأسبوع",
        "sec_history":         "سجل آخر 30 يوماً",
        "kpi_sold":            "الوحدات المباعة",
        "kpi_yesterday":       "مقارنة بالأمس",
        "kpi_avg":             "مقارنة بالمعدل",
        "kpi_best":            "أفضل منتج اليوم",
        "kpi_avg_day":         "المعدل اليومي",
        "kpi_best_day_ever":   "أفضل يوم",
        "kpi_open_days":       "أيام العمل",
        "kpi_yesterday_sub":   "أمس : {qty} {u}",
        "kpi_avg_sub":         "المعدل : {avg:.0f} {u}/ي",
        "perf_good":           "يوم ممتاز ⭐",
        "perf_avg":            "يوم عادي 📊",
        "perf_bad":            "يوم ضعيف ⚠️",
        "perf_good_sub":       "أعلى بكثير من المعدل",
        "perf_avg_sub":        "ضمن النطاق المعتاد",
        "perf_bad_sub":        "أقل من المعدل",
        "perf_vs":             "من المعدل",
        "rank_pos":            "#",
        "rank_product":        "المنتج",
        "rank_total":          "إجمالي المبيعات",
        "rank_share":          "الحصة",
        "rank_trend":          "الاتجاه",
        "rank_caption":        "↗ ارتفاع · → مستقر · ↘ انخفاض (مقارنة آخر 30 يوم بـ30 يوم سابقة)",
        "hist_date":           "التاريخ",
        "hist_day":            "اليوم",
        "hist_qty":            "الكمية",
        "hist_vs_avg":         "مقارنة",
        "hist_perf":           "التقييم",
        "days":                ["إث","ثل","أر","خم","جم","سب","أح"],
        "units":               "وحدة",
        "lang_label":          "اللغة",
        # ── Saisie ───────────────────────────────────────────────────────────
        "saisie_title":        "إدخال المبيعات",
        "saisie_sub":          "أدخل مبيعات اليوم دون تعديل ملف CSV. ثم حمّل الملف الكامل لإعادة استيراده.",
        "saisie_nofile":       "لا يوجد ملف — يمكنك إدخال المبيعات يدوياً.",
        "saisie_new_prod":     "إضافة منتج إلى القائمة",
        "saisie_add_btn":      "إضافة",
        "saisie_date_label":   "تاريخ المبيعات",
        "saisie_save_btn":     "حفظ المبيعات",
        "saisie_save_btn2":    "حفظ",
        "saisie_sec_entry":    "مبيعات اليوم",
        "saisie_history":      "سجل الإدخالات اليدوية",
        "saisie_export":       "تصدير / مزامنة",
        "saisie_sync_tip":     "💡 يتم حفظ إدخالاتك خلال هذه الجلسة. حمّل الملف الكامل أدناه وأعد استيراده في الجلسة التالية.",
        "saisie_download":     "تحميل الملف الكامل (CSV + الإدخالات)",
        "saisie_clear":        "مسح الكل",
        "saisie_empty":        "لا توجد إدخالات يدوية حتى الآن. استخدم النموذج أعلاه.",
        "saisie_success":      "تم حفظ {n} منتج(ات) بتاريخ {d}.",
        "saisie_warn":         "أدخل كمية > 0 على الأقل.",
        "saisie_kpi_days":     "أيام مُدخلة",
        "saisie_kpi_days_sub": "عبر الإدخال اليدوي",
        "saisie_kpi_total":    "إجمالي مُدخل",
        "saisie_kpi_total_sub":"وحدات إجمالاً",
        "saisie_already_csv":  "موجود بالفعل في CSV لهذا التاريخ.",
        "dialog_add_title":    "إضافة مبيعات",
        "dialog_add_sub":      "تُحفظ الإدخالات خلال الجلسة. صدّر CSV للاحتفاظ بها.",
        "dialog_btn_open":     "+ إضافة مبيعات",
        # ── Forecast ─────────────────────────────────────────────────────────
        "forecast_title":      "توقعات المبيعات",
        "forecast_sub":        "توقعات مدعومة بالذكاء الاصطناعي مع مراعاة العطل المغربية.",
        "forecast_lite_banner":"⚡ الوضع الاقتصادي مفعّل — توقعات الذكاء الاصطناعي معطلة.",
        "forecast_lite_section":"الاتجاه الأخير (آخر 30 يوم)",
        "forecast_horizon":    "كم عدد الأيام؟",
        "forecast_horizon_fmt":"{n} يوم",
        "forecast_acc_good":   "ممتازة",
        "forecast_acc_ok":     "جيدة",
        "forecast_acc_fair":   "مقبولة",
        "forecast_acc_na":     "غير متاح",
        "forecast_acc_sub":    "خطأ متوسط : {mae} وحدة/يوم",
        "forecast_acc_label":  "دقة التوقعات",
        "forecast_acc_nodata": "بيانات غير كافية",
        "forecast_spinner":    "جارٍ تحميل التوقعات...",
        "forecast_chart_sec":  "السجل التاريخي + توقع {n} يوم",
        "forecast_history":    "مبيعات سابقة",
        "forecast_pred":       "توقع الذكاء الاصطناعي",
        "forecast_range":      "النطاق المتوقع",
        "forecast_fc_start":   "بداية التوقع ({d})",
        "forecast_peaks":      "تنبيهات — ذروات وشيكة",
        "forecast_ram_sec":    "وضع رمضان — الأيام المعنية",
        "forecast_ram_msg":    "**{n} يوم** من التوقع يقع في رمضان. مبيعات المساء (الإفطار) قد تمثل 60-80% من الرقم اليومي. جهّز المزيد من **الحريرة والشباكية والبريوات** والمشروبات الحلوة.",
        "forecast_weekly":     "ملخص أسبوعي",
        "forecast_monthly":    "ملخص شهري",
        "forecast_weekly_cols":["الأسبوع","الأيام","الإجمالي","معدل/يوم","الحد الأدنى","الحد الأقصى"],
        "forecast_monthly_cols":["الشهر","الإجمالي","معدل/يوم","الحد الأدنى","الحد الأقصى"],
        # ── Recommendations ───────────────────────────────────────────────────
        "reco_title":          "المخزون للتحضير",
        "reco_sub":            "7 أيام القادمة · هامش +15%",
        "reco_spinner":        "جارٍ حساب خطة المخزون...",
        "reco_summary":        "{total} وحدة للتحضير هذا الأسبوع",
        "reco_summary_sub":    "توقع : {pred} + 15% هامش",
        "reco_plan":           "الخطة اليومية",
        "reco_col_date":       "التاريخ",
        "reco_col_day":        "اليوم",
        "reco_col_expected":   "المبيعات المتوقعة",
        "reco_col_stock":      "للتحضير",
        "reco_col_peak":       "يوم ذروة",
        "reco_col_risk":       "المخاطرة",
        "reco_risk_high":      "عالٍ",
        "reco_risk_med":       "متوسط",
        "reco_risk_low":       "منخفض",
        "reco_footer":         "المعدل اليومي : {avg} وحدة · هامش : +15% · عالٍ = +30% من المعدل",
        "reco_no_peak":        "لا توجد ذروات استثنائية. عمليات عادية موصى بها.",
        # ── Analyse ──────────────────────────────────────────────────────────
        "analyse_title":       "تحليل متقدم",
        "analyse_sub":         "مقارنة الأسابيع، توقعات المنتجات، تقويم الأعياد المغربية وأفضل ساعة بيع.",
        "analyse_spinner":     "جارٍ حساب التوقعات...",
        "analyse_week":        "الأسبوع الحالي مقابل الأسبوع الماضي",
        "analyse_cur_week":    "الأسبوع الحالي",
        "analyse_cur_week_sub":"آخر 7 أيام",
        "analyse_prev_week":   "الأسبوع الماضي",
        "analyse_prev_week_sub":"7 أيام سابقة",
        "analyse_delta":       "التطور",
        "analyse_units_sold":  "وحدات مباعة",
        "analyse_hour":        "أفضل ساعة بيع",
        "analyse_best_hour":   "أفضل ساعة",
        "analyse_peak_avg":    "ذروة متوسطة : {qty:.1f} وحدة",
        "analyse_no_hour":     "لتفعيل هذه الميزة، أضف عموداً **`heure`** (0-23) إلى ملف CSV.",
        "analyse_prod":        "توقع حسب المنتج",
        "analyse_prod_pick":   "اختر منتجاً",
        "analyse_horizon":     "الأفق",
        "analyse_horizon_fmt": "{n} يوم",
        "analyse_prod_lite":   "⚡ الوضع الاقتصادي — توقعات المنتجات معطلة.",
        "analyse_prod_empty":  "لا توجد منتجات في بياناتك.",
        "analyse_prod_nodata": "بيانات غير كافية لـ **{p}** ({n} يوم — الحد الأدنى 30).",
        "analyse_prod_spinner":"توقع لـ {p}...",
        "analyse_prod_hist":   "المتوسط التاريخي",
        "analyse_prod_next7":  "متوقع (7 أيام القادمة)",
        "analyse_prod_units":  "وحدة/يوم (أيام مفتوحة)",
        "analyse_prod_total":  "وحدات إجمالاً",
        "analyse_interval":    "النطاق",
        "analyse_pred_label":  "توقع ذكاء اصطناعي",
        "analyse_hist_label":  "السجل التاريخي",
        "analyse_fc_start":    "بداية التوقع",
        "analyse_calendar":    "تقويم الأعياد المغربية",
        "analyse_cal_nat":     "عيد وطني",
        "analyse_cal_isl":     "عيد إسلامي",
        "analyse_cal_ram":     "رمضان",
        "analyse_ram_msg":     "**وضع رمضان مفعّل** — خلال رمضان، تتركز مبيعاتك في الفترة **19:00 – 23:00** (الإفطار والتراويح). جهّز المزيد من: الحريرة، الشباكية، السلو، البريوات، العصائر الطازجة والتمر. قلّل التحضيرات الصباحية بنسبة 30–40%.",
        "analyse_trend_up":    "ارتفاع",
        "analyse_trend_stable":"مستقر",
        "analyse_trend_down":  "انخفاض",
        "analyse_trend_caption":"↗ {up} · → {stable} · ↘ {down}",
        # ── Overview ─────────────────────────────────────────────────────────
        "overview_title":      "نظرة عامة",
        "overview_sub":        "{n} صف · {start} → {end}",
        "overview_kpi_total":  "إجمالي المبيعات",
        "overview_kpi_best":   "أفضل منتج",
        "overview_kpi_avg":    "المعدل اليومي",
        "overview_kpi_busiest":"أكثر الأيام ازدحاماً",
        "overview_trend":      "اتجاه المبيعات",
        "overview_filter":     "تصفية الفترة",
        "overview_breakdown":  "توزيع المنتجات",
        "overview_health":     "صحة البيانات",
        "overview_health_ok":  "موافق",
        "overview_health_warn":"تحذير",
        "overview_health_err": "خطأ",
        # ── Finances ─────────────────────────────────────────────────────────
        "fin_title":           "المالية والربحية",
        "fin_sub":             "رقم الأعمال والهوامش والأهداف وتقدير الربح الشهري.",
        "fin_config":          "تهيئة أسعار البيع وتكاليف الإنتاج",
        "fin_config_caption":  "أدخل **سعر البيع** (ما تحصله) و**التكلفة الوحدوية** (مكونات + تغليف) لكل منتج. جميع القيم بالدرهم (MAD).",
        "fin_auto_price":      "تم اكتشاف عمود `prix_unitaire` — تم تعبئة الأسعار تلقائياً.",
        "fin_col_prod":        "المنتج",
        "fin_col_price":       "سعر البيع (MAD)",
        "fin_col_cost":        "التكلفة الوحدوية (MAD)",
        "fin_col_price_help":  "السعر الذي تبيع به الوحدة",
        "fin_col_cost_help":   "إجمالي تكلفة المكونات والتغليف لكل وحدة",
        "fin_warn_no_price":   "لم يتم تهيئة أي أسعار — ستعرض المقاييس المالية 0 درهم.",
        "fin_ca_section":      "رقم الأعمال",
        "fin_kpi_day":         "CA اليوم",
        "fin_kpi_week":        "CA الأسبوع",
        "fin_kpi_month":       "CA الشهر",
        "fin_kpi_margin":      "الهامش الشهري",
        "fin_margin_sub":      "الهامش : {m}",
        "fin_margin_pct":      "{pct:.1f}% من CA",
        "fin_target_section":  "هدف CA اليومي",
        "fin_target_input":    "الهدف (MAD/يوم)",
        "fin_target_above":    "{pct:.0f}% محقق · {ca} / الهدف {target}",
        "fin_target_days":     "أيام تحقق الهدف في السجل : **{n} / {total}**",
        "fin_target_empty":    "أدخل هدفاً على اليسار لرؤية تقدمك.",
        "fin_ca_series":       "CA اليومي",
        "fin_cost_series":     "تكلفة المواد",
        "fin_target_line":     "الهدف {t}/يوم",
        "fin_prod_section":    "المنتج الأكثر ربحاً مقابل الأكثر مبيعاً",
        "fin_best_seller":     "الأكثر مبيعاً",
        "fin_best_margin":     "الأكثر ربحاً",
        "fin_bubble_x":        "الوحدات المباعة",
        "fin_bubble_y":        "الهامش / الوحدة (MAD)",
        "fin_bubble_size":     "إجمالي CA (MAD)",
        "fin_table_cols":      ["المنتج","الوحدات المباعة","إجمالي CA","إجمالي التكلفة","الهامش الإجمالي","الهامش %","الهامش/وحدة"],
        "fin_no_price_info":   "أعد تهيئة الأسعار أعلاه لرؤية هذا التحليل.",
        "fin_monthly_section": "الإيرادات مقابل تكاليف المواد",
        "fin_rev_series":      "الإيرادات (CA)",
        "fin_mp_series":       "تكلفة المواد",
        "fin_margin_series":   "الهامش الإجمالي",
        "fin_profit_section":  "تقدير الربح الشهري",
        "fin_month_cols":      ["الشهر","CA (MAD)","المواد (MAD)","الهامش (MAD)","الهامش %"],
        "fin_total_sub":       "CA : {ca} · تكلفة المواد : {cout} · النسبة : {pct:.1f}%",
        "fin_total_label":     "إجمالي الهامش على كامل الفترة",
        "fin_no_config_info":  "أعد تهيئة الأسعار والتكاليف أعلاه لتفعيل هذا القسم.",
        "fin_footer":          "الهامش الإجمالي = CA − تكلفة المواد. لا يشمل الإيجار أو الرواتب أو التكاليف الثابتة.",
        # ── Products ─────────────────────────────────────────────────────────
        "products_title":          "منتجاتي",
        "products_sub":            "فعّل/عطّل المنتجات في الحسابات والتوقعات.",
        "products_kpi_total":      "إجمالي المنتجات",
        "products_kpi_active":     "المنتجات النشطة",
        "products_kpi_custom":     "أضفتها أنت",
        "products_list_title":     "قائمة المنتجات",
        "products_list_caption":   "تأشير/إلغاء تأشير **نشط** لتضمين أو استبعاد منتج. منتجات CSV لا يمكن حذفها.",
        "products_col_dish":       "المنتج",
        "products_col_source":     "المصدر",
        "products_col_share":      "حصة المبيعات",
        "products_col_recipe":     "الوصفة",
        "products_col_active":     "نشط",
        "products_source_csv":     "من بياناتك",
        "products_source_custom":  "أضفته أنت",
        "products_add_title":      "إضافة منتج",
        "products_add_caption":    "أضف منتجاً غير موجود في CSV. حدّد مكوناته في قائمة التسوق.",
        "products_add_placeholder":"مثال: بطاطا مقلية...",
        "products_add_btn":        "إضافة",
        "products_add_exists":     "**{name}** موجود بالفعل في كتالوجك.",
        "products_add_success":    "تمت إضافة **{name}**! حدّد مكوناته في قائمة التسوق.",
        "products_del_title":      "حذف منتج",
        "products_del_caption":    "يمكن حذف المنتجات المضافة يدوياً فقط.",
        "products_del_btn":        "حذف",
        "products_info":           "منتجات CSV يمكن تعطيلها فقط لا حذفها — سجلها مطلوب للتوقعات.",
        # ── Shopping list ─────────────────────────────────────────────────────
        "shop_title":              "قائمة التسوق",
        "shop_sub":                "المكونات لـ7 أيام القادمة بناءً على وصفاتك وتوقعاتك.",
        "shop_ingredients_title":  "المكونات لكل طبق",
        "shop_ingredients_caption":"الكميات لحصة واحدة. قابلة للتعديل بحرية.",
        "shop_stock_title":        "ما لديك بالفعل",
        "shop_stock_caption":      "أدخل مخزونك الحالي. فقط الناقص سيظهر في الطلب.",
        "shop_needs_title":        "الاحتياجات اليومية — 7 أيام القادمة",
        "shop_order_title":        "ماذا تشتري",
        "shop_stockout_title":     "متى ستنفد المخزون؟",
        "shop_kpi_tobuy":          "مكونات للشراء",
        "shop_kpi_ok":             "في المخزون بالفعل",
        "shop_kpi_first":          "أول نقص",
        "shop_col_ing":            "المكون",
        "shop_col_unit":           "الوحدة",
        "shop_col_need":           "احتياج 7أ (+15%)",
        "shop_col_have":           "في المخزون",
        "shop_col_buy":            "للشراء",
        "shop_col_status":         "الحالة",
        "shop_status_ok":          "موافق",
        "shop_status_order":       "اطلب",
        "shop_status_critical":    "حرج",
        "shop_col_instock":        "في المخزون",
        "shop_col_perday":         "مستهلك/يوم",
        "shop_col_runout":         "تاريخ النفاد",
        "shop_col_urgency":        "الأولوية",
        "shop_urg_ok":             "موافق",
        "shop_urg_soon":           "قريباً جداً",
        "shop_urg_week":           "هذا الأسبوع",
        "shop_urg_later":          "لاحقاً",
        "shop_caption":            "الحاجة = توقع × مكونات × +15% هامش · للشراء = الحاجة − المخزون",
        "shop_no_ing":             "لا مكونات محددة. امل الجدول أعلاه.",
        "shop_spinner":            "جارٍ حساب احتياجاتك...",
        # ── Conseils ─────────────────────────────────────────────────────────
        "conseils_hero_title": "مساعدة في اتخاذ القرار",
        "conseils_hero_sub":   "نصائح مخصصة بناءً على سجلك — تُحدَّث في الوقت الفعلي.",
        "conseils_pdj":        "⭐ منتج اليوم المقترح للإبراز",
        "conseils_pdj_badge":  "أبرزه اليوم",
        "conseils_pdj_score":  "النقاط {s}/100 | متوسط {d} : {qty:.0f} وحدة{margin}",
        "conseils_pdj_margin": " | الهامش : {m:.1f} درهم/وحدة",
        "conseils_pdj_empty":  "بيانات غير كافية لحساب منتج اليوم.",
        "conseils_prep":       "📋 جهّز أكثر — الأيام السبعة القادمة",
        "conseils_prep_normal":"يوم عادي — لا توجد ذروات محددة.",
        "conseils_promo":      "🏷️ اقتراحات أسعار ترويجية",
        "conseils_promo_thresh":"عتبة الانخفاض لتشغيل العرض (%)",
        "conseils_promo_help": "يُشار إلى المنتج إذا انخفضت مبيعاته خلال 7 أيام بنسبة X% مقارنة بـ30 يوماً.",
        "conseils_promo_note": "السعر الترويجي محسوب بتطبيق الخصم على سعر الوحدة المُهيأ في المالية.",
        "conseils_promo_config":"أعد تهيئة السعر",
        "conseils_promo_ok":   "✅ لا يوجد منتج في انخفاض ملحوظ خلال 7 أيام الأخيرة.",
        "conseils_dormant":    "😴 تنبيهات — منتجات لم تُباع مؤخراً",
        "conseils_dormant_slider":"التنبيه إذا كان غائباً منذ (أيام)",
        "conseils_dormant_help":"يُشار إلى المنتج إذا لم يظهر في مبيعاتك منذ X أيام.",
        "conseils_dormant_since":"آخر بيع : {d} — غائب منذ {n} أيام",
        "conseils_dormant_never":"آخر بيع : لم يُباع قط — غائب منذ +{n} أيام",
        "conseils_dormant_ok": "✅ جميع المنتجات بيعت خلال الأيام الأخيرة.",
        "conseils_seasonal":   "🌿 أفكار منتجات جديدة — الموسم والمناسبات",
        "conseils_seasonal_note":"اقتراحات بناءً على اتجاهات السوق المغربي والموسمية المحلية.",
        "conseils_seasonal_empty":"لا توجد اقتراحات موسمية لهذه الفترة.",
        "conseils_ram_current":"رمضان — الآن",
        "conseils_ram_soon":   "رمضان — خلال 30 يوماً",
        "conseils_month_now":  "{m} — منتجات موسمية",
        "conseils_month_next": "{m} — استعد للشهر القادم",
        # ── About ─────────────────────────────────────────────────────────────
        "about_title":         "حول",
        "about_what_title":    "ما هو FoodCast؟",
        "about_what_body":     "لوحة تحكم لتوقعات المبيعات للمطاعم الصغيرة. استورد سجل CSV، احصل على توقعات Prophet، وقرر ماذا تحضر وتشتري — دون مهارات تقنية.",
        "about_format_title":  "تنسيق ملف CSV",
        "about_dl_sample":     "تحميل CSV تجريبي",
        "about_stack_title":   "بُني بـ",
        "about_version":       "v{v} · FoodCast © 2025",
        # ── Sub-tabs ──────────────────────────────────────────────────────────
        "tab_ranking":         "الترتيب",
        "tab_conseils":        "النصائح",
        "tab_forecast_global": "التوقع الشامل",
        "tab_reco":            "المخزون للتحضير",
        "tab_per_product":     "حسب المنتج",
        "tab_shopping":        "قائمة التسوق",
        "tab_overview":        "نظرة عامة",
        "tab_trends":          "الاتجاهات",
        "tab_catalogue":       "الكتالوج",
    },

    "en": {
        # ── Main navigation ───────────────────────────────────────────────────
        "nav_today":       "Today",
        "nav_forecasts":   "Forecasts",
        "nav_finance":     "Finances",
        "nav_analytics":   "Analytics",
        # ── Legacy ───────────────────────────────────────────────────────────
        "nav_dashboard":       "Dashboard",
        "nav_saisie":          "Sales Entry",
        "nav_overview":        "Overview",
        "nav_forecast":        "Forecast",
        "nav_analyse":         "Analytics",
        "nav_finances":        "Finances",
        "nav_recommendations": "Recommendations",
        "nav_products":        "Products",
        "nav_shopping":        "Shopping List",
        "nav_conseils":        "Insights",
        "nav_about":           "About",
        # ── Sidebar ───────────────────────────────────────────────────────────
        "sidebar_file":        "SALES FILE",
        "sidebar_demo":        "Boulangerie Atlas (demo) — upload your file above.",
        "sidebar_ramadan":     "Ramadan Mode",
        "sidebar_ramadan_help":"Enable Iftar alerts, special product indicators and Ramadan markers on charts.",
        "sidebar_lite":        "Lite Mode",
        "sidebar_lite_help":   "Disable AI forecasts (Prophet) to save bandwidth. Ideal on slow connections.",
        # ── Onboarding ────────────────────────────────────────────────────────
        "onboard_title":       "Welcome to FoodCast",
        "onboard_sub":         "Import your sales to see forecasts and insights in real time.",
        "onboard_load_btn":    "Load a CSV",
        "onboard_demo_btn":    "Use demo data",
        "onboard_demo_hint":   "Boulangerie Atlas · 27 months · 12 products",
        # ── Dashboard ─────────────────────────────────────────────────────────
        "dash_title":          "Dashboard",
        "sec_today":           "Today's Summary",
        "sec_perf":            "Performance Indicator",
        "sec_ranking":         "Product Ranking",
        "sec_week":            "This Week's Sales",
        "sec_history":         "History — Last 30 Days",
        "kpi_sold":            "Units Sold",
        "kpi_yesterday":       "vs yesterday",
        "kpi_avg":             "vs average",
        "kpi_best":            "Best Product Today",
        "kpi_avg_day":         "Avg / open day",
        "kpi_best_day_ever":   "All-time record",
        "kpi_open_days":       "Open days",
        "kpi_yesterday_sub":   "yesterday: {qty} {u}",
        "kpi_avg_sub":         "avg: {avg:.0f} {u}/day",
        "perf_good":           "Great day",
        "perf_avg":            "Average day",
        "perf_bad":            "Slow day",
        "perf_good_sub":       "Well above average",
        "perf_avg_sub":        "Within normal range",
        "perf_bad_sub":        "Below average",
        "perf_vs":             "of average",
        "rank_pos":            "#",
        "rank_product":        "Product",
        "rank_total":          "Total sold",
        "rank_share":          "Share",
        "rank_trend":          "Trend",
        "rank_caption":        "↗ rising · → stable · ↘ declining (last 30 days vs previous 30 days)",
        "hist_date":           "Date",
        "hist_day":            "Day",
        "hist_qty":            "Quantity",
        "hist_vs_avg":         "vs avg",
        "hist_perf":           "Rating",
        "days":                ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
        "units":               "units",
        "lang_label":          "Language",
        # ── Saisie ───────────────────────────────────────────────────────────
        "saisie_title":        "Sales Entry",
        "saisie_sub":          "Enter today's sales without editing your CSV. Download the full file afterwards to re-import it.",
        "saisie_nofile":       "No file loaded — you can enter sales manually. Download the generated CSV and import it as your data file.",
        "saisie_new_prod":     "Add a product to the list",
        "saisie_add_btn":      "Add",
        "saisie_date_label":   "Sales date",
        "saisie_save_btn":     "Save sales",
        "saisie_save_btn2":    "Save",
        "saisie_sec_entry":    "Today's sales",
        "saisie_history":      "Manual entry history",
        "saisie_export":       "Export / Sync",
        "saisie_sync_tip":     "💡 Your entries are kept during this session. Download the full file below to keep them, then import it at next launch.",
        "saisie_download":     "Download full file (CSV + entries)",
        "saisie_clear":        "Clear all",
        "saisie_empty":        "No manual entries yet. Use the form above.",
        "saisie_success":      "{n} product(s) saved for {d}.",
        "saisie_warn":         "Enter at least one quantity > 0.",
        "saisie_kpi_days":     "Days entered",
        "saisie_kpi_days_sub": "via manual entry",
        "saisie_kpi_total":    "Total entered",
        "saisie_kpi_total_sub":"units total",
        "saisie_already_csv":  "Already in your CSV for this date.",
        "dialog_add_title":    "Add sales",
        "dialog_add_sub":      "Entries are kept during this session. Export CSV to keep them.",
        "dialog_btn_open":     "+ Add sales",
        # ── Forecast ─────────────────────────────────────────────────────────
        "forecast_title":      "Sales Forecast",
        "forecast_sub":        "AI-powered forecasts with Moroccan holiday awareness.",
        "forecast_lite_banner":"⚡ Lite mode on — AI forecasts disabled. Turn it off in the sidebar to see Prophet forecasts.",
        "forecast_lite_section":"Recent trend (last 30 days)",
        "forecast_horizon":    "How many days ahead?",
        "forecast_horizon_fmt":"{n} days",
        "forecast_acc_good":   "Very Good",
        "forecast_acc_ok":     "Good",
        "forecast_acc_fair":   "Fair",
        "forecast_acc_na":     "N/A",
        "forecast_acc_sub":    "avg error: {mae} units/day",
        "forecast_acc_label":  "Forecast accuracy",
        "forecast_acc_nodata": "Not enough data",
        "forecast_spinner":    "Loading your forecast...",
        "forecast_chart_sec":  "Sales History + {n}-Day Forecast",
        "forecast_history":    "Past sales",
        "forecast_pred":       "AI prediction",
        "forecast_range":      "Expected range",
        "forecast_fc_start":   "Forecast start ({d})",
        "forecast_peaks":      "Alerts — Upcoming peaks",
        "forecast_ram_sec":    "Ramadan Mode — Affected Days",
        "forecast_ram_msg":    "**{n} days** in the forecast fall during Ramadan. Evening sales (Iftar) may represent 60–80% of daily revenue. Prepare more **Harira, Chebakia, Briouates** and sweet drinks.",
        "forecast_weekly":     "Weekly summary",
        "forecast_monthly":    "Monthly summary",
        "forecast_weekly_cols":["Week","Days","Total forecast","Avg/day","Min forecast","Max forecast"],
        "forecast_monthly_cols":["Month","Total forecast","Avg/day","Min forecast","Max forecast"],
        # ── Recommendations ───────────────────────────────────────────────────
        "reco_title":          "Stock to prepare",
        "reco_sub":            "Next 7 days · +15% buffer",
        "reco_spinner":        "Calculating your stock plan...",
        "reco_summary":        "{total} units to prepare this week",
        "reco_summary_sub":    "forecast: {pred} + 15% buffer",
        "reco_plan":           "Daily plan",
        "reco_col_date":       "Date",
        "reco_col_day":        "Day",
        "reco_col_expected":   "Expected sales",
        "reco_col_stock":      "To prepare",
        "reco_col_peak":       "Peak day",
        "reco_col_risk":       "Risk",
        "reco_risk_high":      "High",
        "reco_risk_med":       "Medium",
        "reco_risk_low":       "Low",
        "reco_footer":         "Daily avg: {avg} units · buffer: +15% · High = +30% vs avg · Min/Max = confidence range",
        "reco_no_peak":        "No extraordinary peaks forecast. Normal operations recommended.",
        # ── Analyse ──────────────────────────────────────────────────────────
        "analyse_title":       "Advanced Analytics",
        "analyse_sub":         "Week comparison, per-product forecasts, Moroccan holiday calendar and best selling hour.",
        "analyse_spinner":     "Computing forecasts...",
        "analyse_week":        "This week vs last week",
        "analyse_cur_week":    "This week",
        "analyse_cur_week_sub":"Last 7 days",
        "analyse_prev_week":   "Last week",
        "analyse_prev_week_sub":"Previous 7 days",
        "analyse_delta":       "Change",
        "analyse_units_sold":  "Units sold",
        "analyse_hour":        "Best selling hour",
        "analyse_best_hour":   "Best hour",
        "analyse_peak_avg":    "Peak avg: {qty:.1f} units",
        "analyse_no_hour":     "To enable this, add an **`heure`** column (0–23) to your CSV. Example: `2024-01-15, Pizza Margherita, 12, 8`",
        "analyse_prod":        "Per-product forecast",
        "analyse_prod_pick":   "Choose a product",
        "analyse_horizon":     "Horizon",
        "analyse_horizon_fmt": "{n} days",
        "analyse_prod_lite":   "⚡ Lite mode — per-product forecasts disabled.",
        "analyse_prod_empty":  "No products found in your data.",
        "analyse_prod_nodata": "Not enough data for **{p}** ({n} days — minimum 30).",
        "analyse_prod_spinner":"Forecasting {p}...",
        "analyse_prod_hist":   "Historical avg",
        "analyse_prod_next7":  "Forecast (next 7 days)",
        "analyse_prod_units":  "units/day (open days)",
        "analyse_prod_total":  "units total",
        "analyse_interval":    "Expected range",
        "analyse_pred_label":  "AI Forecast",
        "analyse_hist_label":  "History",
        "analyse_fc_start":    "Forecast start",
        "analyse_calendar":    "Moroccan Holiday Calendar",
        "analyse_cal_nat":     "National holiday",
        "analyse_cal_isl":     "Islamic holiday",
        "analyse_cal_ram":     "Ramadan",
        "analyse_ram_msg":     "**Ramadan mode on** — During Ramadan, sales concentrate in the **7 PM – 11 PM** window (Iftar & Tarawih). Prepare more: Harira, Chebakia, Sellou, Briouates, Shabakiya, fresh juices and dates. Reduce morning prep by 30–40%.",
        "analyse_trend_up":    "rising",
        "analyse_trend_stable":"stable",
        "analyse_trend_down":  "declining",
        "analyse_trend_caption":"↗ {up} · → {stable} · ↘ {down} (last 30 days vs previous 30 days)",
        # ── Overview ─────────────────────────────────────────────────────────
        "overview_title":      "Overview",
        "overview_sub":        "{n} rows · {start} → {end}",
        "overview_kpi_total":  "Total sold",
        "overview_kpi_best":   "Best product",
        "overview_kpi_avg":    "Daily avg",
        "overview_kpi_busiest":"Busiest day",
        "overview_trend":      "Sales trend",
        "overview_filter":     "Filter period",
        "overview_breakdown":  "Product breakdown",
        "overview_health":     "Data health",
        "overview_health_ok":  "OK",
        "overview_health_warn":"Warning",
        "overview_health_err": "Error",
        # ── Finances ─────────────────────────────────────────────────────────
        "fin_title":           "Finances & Profitability",
        "fin_sub":             "Revenue, margins, targets and monthly profit estimate.",
        "fin_config":          "Configure selling prices and unit costs",
        "fin_config_caption":  "Enter the **selling price** (what you collect) and **unit cost** (ingredients + packaging) for each product. All values in **MAD**.",
        "fin_auto_price":      "`prix_unitaire` column detected — prices pre-filled.",
        "fin_col_prod":        "Product",
        "fin_col_price":       "Selling price (MAD)",
        "fin_col_cost":        "Unit cost (MAD)",
        "fin_col_price_help":  "Price at which you sell one portion/unit",
        "fin_col_cost_help":   "Total ingredient + packaging cost per unit produced",
        "fin_warn_no_price":   "No selling prices set — financial metrics will show 0 MAD. Enter prices in the table above to unlock all analyses.",
        "fin_ca_section":      "Revenue",
        "fin_kpi_day":         "Today's revenue",
        "fin_kpi_week":        "This week's revenue",
        "fin_kpi_month":       "This month's revenue",
        "fin_kpi_margin":      "Monthly gross margin",
        "fin_margin_sub":      "margin: {m}",
        "fin_margin_pct":      "{pct:.1f}% of revenue",
        "fin_target_section":  "Daily revenue target",
        "fin_target_input":    "Target (MAD/day)",
        "fin_target_above":    "{pct:.0f}% achieved · {ca} / target {target}",
        "fin_target_days":     "Days that hit the target in history: **{n} / {total}**",
        "fin_target_empty":    "Enter a target on the left to track your progress.",
        "fin_ca_series":       "Daily revenue",
        "fin_cost_series":     "Raw material cost",
        "fin_target_line":     "Target {t}/day",
        "fin_prod_section":    "Most profitable vs best-selling product",
        "fin_best_seller":     "Best seller",
        "fin_best_margin":     "Most profitable",
        "fin_bubble_x":        "Units sold",
        "fin_bubble_y":        "Margin / unit (MAD)",
        "fin_bubble_size":     "Total revenue (MAD)",
        "fin_table_cols":      ["Product","Units sold","Total revenue","Total cost","Gross margin","Margin %","Margin/unit"],
        "fin_no_price_info":   "Set up prices above to see this analysis.",
        "fin_monthly_section": "Revenue vs raw material costs",
        "fin_rev_series":      "Revenue",
        "fin_mp_series":       "Raw material cost",
        "fin_margin_series":   "Gross margin",
        "fin_profit_section":  "Monthly profit estimate",
        "fin_month_cols":      ["Month","Revenue (MAD)","Materials (MAD)","Margin (MAD)","Margin %"],
        "fin_total_sub":       "Revenue: {ca} · Materials: {cout} · Rate: {pct:.1f}%",
        "fin_total_label":     "Total gross margin over the entire period",
        "fin_no_config_info":  "Set up prices and costs above to enable this section.",
        "fin_footer":          "Gross margin = Revenue − Raw material costs. Does not include rent, payroll or fixed costs. A gross margin ≥ 60% is generally healthy for food businesses.",
        # ── Products ─────────────────────────────────────────────────────────
        "products_title":          "My products",
        "products_sub":            "Activate or deactivate products in calculations and forecasts.",
        "products_kpi_total":      "Total products",
        "products_kpi_active":     "Active products",
        "products_kpi_custom":     "Added by you",
        "products_list_title":     "Product list",
        "products_list_caption":   "Check/uncheck **Active** to include or exclude a product. CSV products cannot be deleted.",
        "products_col_dish":       "Product",
        "products_col_source":     "Source",
        "products_col_share":      "Sales share",
        "products_col_recipe":     "Recipe",
        "products_col_active":     "Active",
        "products_source_csv":     "From your data",
        "products_source_custom":  "Added by you",
        "products_add_title":      "Add a product",
        "products_add_caption":    "Add a product not in your CSV. Set up ingredients on the Shopping List.",
        "products_add_placeholder":"e.g. French Fries, Nuggets…",
        "products_add_btn":        "Add",
        "products_add_exists":     "**{name}** is already in your catalogue.",
        "products_add_success":    "**{name}** added! Set up ingredients on the Shopping List.",
        "products_del_title":      "Remove a product",
        "products_del_caption":    "Only manually added products can be removed.",
        "products_del_btn":        "Delete",
        "products_info":           "CSV products can be deactivated but not deleted — their history is needed for forecasts. Manually added products can be freely removed.",
        # ── Shopping list ─────────────────────────────────────────────────────
        "shop_title":              "Shopping list",
        "shop_sub":                "Ingredients for the next 7 days, from your recipes and forecasts.",
        "shop_ingredients_title":  "Ingredients per dish",
        "shop_ingredients_caption":"Quantities for one serving. Freely edit names, amounts and units.",
        "shop_stock_title":        "What you already have",
        "shop_stock_caption":      "Enter your current stock. Only shortfalls will appear in the order.",
        "shop_needs_title":        "Daily needs — next 7 days",
        "shop_order_title":        "What to buy",
        "shop_stockout_title":     "When will you run out?",
        "shop_kpi_tobuy":          "Ingredients to buy",
        "shop_kpi_ok":             "Already in stock",
        "shop_kpi_first":          "First shortage",
        "shop_col_ing":            "Ingredient",
        "shop_col_unit":           "Unit",
        "shop_col_need":           "Need 7d (+15%)",
        "shop_col_have":           "You have",
        "shop_col_buy":            "To buy",
        "shop_col_status":         "Status",
        "shop_status_ok":          "OK",
        "shop_status_order":       "Order",
        "shop_status_critical":    "Critical",
        "shop_col_instock":        "In stock",
        "shop_col_perday":         "Used per day",
        "shop_col_runout":         "Runs out on",
        "shop_col_urgency":        "Urgency",
        "shop_urg_ok":             "OK",
        "shop_urg_soon":           "Very soon",
        "shop_urg_week":           "This week",
        "shop_urg_later":          "Later",
        "shop_caption":            "Need = forecast × ingredients × +15% buffer · To buy = Need − Stock",
        "shop_no_ing":             "No ingredients defined. Fill in the table above.",
        "shop_spinner":            "Calculating your shopping needs...",
        # ── Conseils ─────────────────────────────────────────────────────────
        "conseils_hero_title": "Decision Support",
        "conseils_hero_sub":   "Personalised insights based on your history — updated in real time.",
        "conseils_pdj":        "⭐ Featured Product of the Day",
        "conseils_pdj_badge":  "Feature today",
        "conseils_pdj_score":  "Score {s}/100 | {d} avg: {qty:.0f} units{margin}",
        "conseils_pdj_margin": " | Margin: {m:.1f} MAD/unit",
        "conseils_pdj_empty":  "Not enough data to compute the product of the day.",
        "conseils_prep":       "📋 Prepare More — Next 7 Days",
        "conseils_prep_normal":"Normal day — no surge identified.",
        "conseils_promo":      "🏷️ Promotional Price Suggestions",
        "conseils_promo_thresh":"Decline threshold to trigger a promo (%)",
        "conseils_promo_help": "A product is flagged if its last-7-day sales dropped by X% vs the previous 30 days.",
        "conseils_promo_note": "Promo price calculated by applying the discount to the unit price set in Finances.",
        "conseils_promo_config":"set price in Finances",
        "conseils_promo_ok":   "✅ No product in significant decline over the last 7 days.",
        "conseils_dormant":    "😴 Alerts — Products Not Sold Recently",
        "conseils_dormant_slider":"Flag if absent for (days)",
        "conseils_dormant_help":"A product is flagged if it hasn't appeared in your sales for X days.",
        "conseils_dormant_since":"Last sale: {d} — absent for {n} days",
        "conseils_dormant_never":"Last sale: never — absent for +{n} days",
        "conseils_dormant_ok": "✅ All products have been sold in recent days.",
        "conseils_seasonal":   "🌿 New Product Ideas — Season & Events",
        "conseils_seasonal_note":"Suggestions based on Moroccan market trends and local seasonality. Adapt them to your clientele.",
        "conseils_seasonal_empty":"No seasonal suggestions available for this period.",
        "conseils_ram_current":"Ramadan — now",
        "conseils_ram_soon":   "Ramadan — in 30 days",
        "conseils_month_now":  "{m} — seasonal products",
        "conseils_month_next": "{m} — prepare for next month",
        # ── About ─────────────────────────────────────────────────────────────
        "about_title":         "About",
        "about_what_title":    "What is FoodCast?",
        "about_what_body":     "Sales forecasting dashboard for small food businesses. Upload your CSV history, get Prophet forecasts, decide what to prepare and buy — no technical skills needed.",
        "about_format_title":  "Your CSV file format",
        "about_dl_sample":     "Download sample CSV",
        "about_stack_title":   "Built with",
        "about_version":       "v{v} · FoodCast © 2025",
        # ── Sub-tabs ──────────────────────────────────────────────────────────
        "tab_ranking":         "Ranking",
        "tab_conseils":        "Insights",
        "tab_forecast_global": "Global forecast",
        "tab_reco":            "Stock to prepare",
        "tab_per_product":     "Per product",
        "tab_shopping":        "Shopping list",
        "tab_overview":        "Overview",
        "tab_trends":          "Trends",
        "tab_catalogue":       "Catalogue",
    },
}

# ── Recipes: ingredient quantities per unit sold ───────────────────────────
RECIPES: dict[str, dict[str, tuple[float, str]]] = {
    "Pain Traditionnel": {
        "Farine de blé":  (250, "g"), "Eau":            (150, "ml"),
        "Levure fraîche": (5,   "g"), "Sel":            (4,   "g"),
        "Huile d'olive":  (8,   "ml"),"Semoule fine":   (30,  "g"),
    },
    "Msemen": {
        "Farine de blé":  (100, "g"), "Semoule fine":   (50,  "g"),
        "Eau tiède":      (70,  "ml"),"Sel":            (2,   "g"),
        "Huile végétale": (15,  "ml"),"Beurre":         (10,  "g"),
    },
    "Harcha": {
        "Semoule fine":   (150, "g"), "Beurre fondu":   (40,  "g"),
        "Lait":           (60,  "ml"),"Sel":            (2,   "g"),
        "Levure chimique":(3,   "g"),
    },
    "Beghrir": {
        "Semoule fine":   (80,  "g"), "Farine de blé":  (40,  "g"),
        "Eau tiède":      (200, "ml"),"Levure fraîche": (5,   "g"),
        "Sel":            (2,   "g"), "Sucre":          (5,   "g"),
    },
    "Croissant": {
        "Farine T45":        (100, "g"), "Beurre de tourage": (55, "g"),
        "Lait":              (35,  "ml"),"Sucre":             (12, "g"),
        "Levure fraîche":    (3,   "g"), "Sel":               (2,  "g"),
        "Oeuf":              (0.2, "piece"),
    },
    "Pain au Chocolat": {
        "Farine T45":        (100, "g"), "Beurre de tourage": (55, "g"),
        "Lait":              (35,  "ml"),"Sucre":             (12, "g"),
        "Levure fraîche":    (3,   "g"), "Sel":               (2,  "g"),
        "Bâton chocolat":    (2,   "piece"),
    },
    "Brioche": {
        "Farine T45":     (150, "g"), "Beurre":         (60,  "g"),
        "Oeuf":           (1.5, "piece"), "Sucre":      (25,  "g"),
        "Levure fraîche": (5,   "g"), "Lait":           (30,  "ml"),
        "Sel":            (3,   "g"),
    },
    "Chausson aux Pommes": {
        "Pâte feuilletée":(120, "g"), "Pomme":          (80,  "g"),
        "Sucre":          (15,  "g"), "Cannelle":        (1,   "g"),
        "Beurre":         (8,   "g"), "Oeuf":            (0.3, "piece"),
    },
    "Mille-feuille": {
        "Pâte feuilletée": (150, "g"), "Crème pâtissière": (120, "g"),
        "Sucre glace":     (20,  "g"), "Fondant blanc":    (30,  "g"),
    },
    "Tarte aux Fraises": {
        "Pâte sablée":     (100, "g"), "Crème pâtissière": (80,  "g"),
        "Fraises":         (120, "g"), "Nappage":           (20,  "g"),
        "Beurre":          (10,  "g"),
    },
    "Eclair au Chocolat": {
        "Pâte à choux":    (80,  "g"), "Crème pâtissière": (90,  "g"),
        "Chocolat noir":   (30,  "g"), "Beurre":           (8,   "g"),
        "Oeuf":            (0.5, "piece"),
    },
    "Sellou": {
        "Farine de blé":  (200, "g"), "Sésame":         (100, "g"),
        "Amandes":        (80,  "g"), "Miel":           (60,  "g"),
        "Beurre fondu":   (80,  "g"), "Anis":           (5,   "g"),
        "Sucre glace":    (40,  "g"),
    },
}
